### ISSUE TITLE
Wait for AGC

### ISSUE THREAD

**Issue by clickworkorange** [O-Hahn/node-red-contrib-camerapi#10]
Great node, very useful! But you should wait a moment after initialising the camera before capturing, so that it has time to adjust the exposure. I was getting incorrectly exposed images until I added a simple 1s sleep in `/home/nodered/.node-red/node_modules/node-red-contrib-camerapi/lib/python/get_photo.py`

        camera.image_effect = imageeffect
        time.sleep(1)
        camera.capture(picfile, i_format)

Further experimentation is required to find the shortest working delay, but 300-800ms seems to be what's needed.

**Comment by clickworkorange** [comment]
See https://github.com/O-Hahn/node-red-contrib-camerapi/pull/12

**Comment by O-Hahn** [comment]
merged into the repo as an enhancement - thx.
