### ISSUE TITLE
Generated photo is black

### ISSUE THREAD

**Issue by NewBermuda** [O-Hahn/node-red-contrib-camerapi#14]
Hi there,

Until last week the camerapi-node just worked fine but now suddenly the image that is created by the node consists of pure blackness. If I take a picture via the commands in the terminal, it works just fine. 
Can you think of possibly causes for this behaviour? Thank you.

**Comment by fitz0019** [comment]
I'm using node-red v0.17.5 and I'm getting the same issue. It worked the first few photos and now they are always black.

**Comment by broo0ose** [comment]
I'm getting the same.  node-red-contrib-camerapi version 0.0.36 , NR version 0.18.7.
it worked a few times then black, raspistill works fine.  
I'm using the original picamera hardware, not the latest one.

**Comment by O-Hahn** [comment]
if have published a new version but i could not verify the same issue. Have you also installed the phyton api? I use this in the phyton library within my script in the system call - and not raspistill .... 
maybe delete the whole node and put it with the new parameters (there are several one including ace) which may cause black images...
