### ISSUE TITLE
"Error: Invalid property expression: zero-length"

### ISSUE THREAD

**Issue by baqwas** [O-Hahn/node-red-contrib-camerapi#24]
Hello,

I have a very, very simple nominal flow to use a PiCamera (sadly v1 still working on securing a V2) on RPi2B as listed below:

`[{"id":"12596fb1.40fcd","type":"inject","z":"95ca61b4.1d4ca","name":"Take Photo","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":100,"y":340,"wires":[["b2ec2b70.c63558"]]},{"id":"b2ec2b70.c63558","type":"camerapi-takephoto","z":"95ca61b4.1d4ca","filemode":"2","filename":"","filedefpath":"1","filepath":"","fileformat":"jpeg","resolution":"2","rotation":"0","fliph":"0","flipv":"0","brightness":"50","contrast":"0","sharpness":"0","quality":"80","imageeffect":"none","exposuremode":"auto","iso":"0","agcwait":"1.0","led":"0","awb":"auto","name":"Capture image","x":280,"y":340,"wires":[["dbebbce7.6079c"]],"inputLabels":["Shutter operation"],"outputLabels":["Image link transfer"]},{"id":"dbebbce7.6079c","type":"image","z":"95ca61b4.1d4ca","name":"","width":"240","x":500,"y":340,"wires":[]}]`

When I click the **Inject** node:

- The node status on the **camerapi** node is briefly highlighted as _Connected_
- The error message "_Error: Invalid property expression: zero-length_" is displayed in the Debug pane

The node referenced in the Debug pane is the **camerapi** (without the name that I assigned to it). I checked all the default parameters including the **Inject** node output payload. There is nothing that I could decipher that would lead to this message unless it is a layer deeper than my cursory understanding of the **camerapi** node.

How can I can proceed to debug the issue, please?

Kind regards.

**Comment by O-Hahn** [comment]
On which version of node-red, nodejs and node-red-contrib-camerapi are you working ? - I had such an issue where the nodejs was too old and node-red also. 
For me it works fine with the most current LTS on Raspi (maybe run the node-red upgrade script)...

**Comment by baqwas** [comment]
OK! Thx for the quick response.

For the record:
`pi@raspbari1:~ $ node-red -v
28 Jan 09:40:04 - [info] 
Welcome to Node-RED
===================
28 Jan 09:40:04 - [info] Node-RED version: v1.0.3
28 Jan 09:40:04 - [info] Node.js  version: v10.15.2
28 Jan 09:40:04 - [info] Linux 4.19.93+ arm LE
`
**camerapi** was installed using **npm** yesterday!

Kind regards.
