### ISSUE TITLE
does not work with Buster 2020-02-13 Error: Cannot find module 'uuid/v4'

### ISSUE THREAD

**Issue by juggledad** [O-Hahn/node-red-contrib-camerapi#27]
RPI 3B
26 May 17:22:16 - [info] Node-RED version: v1.0.6
26 May 17:22:16 - [info] Node.js  version: v12.13.0
26 May 17:22:16 - [info] Linux 4.19.97-v7+ arm LE

This node worked fine in Stretch. Today I flashed a new SD card to Buster and now when I try to use the node the following shows up in a `catch` node

`Error: Cannot find module 'uuid/v4'Require stack:- /home/pi/.node-red/node_modules/node-red-contrib-camerapi/camerapi.js- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js- /usr/lib/node_modules/node-red/lib/red.js- /usr/lib/node_modules/node-red/red.js`

and msg.stack shows:
`Error: Cannot find module 'uuid/v4'Require stack:- /home/pi/.node-red/node_modules/node-red-contrib-camerapi/camerapi.js- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js- /usr/lib/node_modules/node-red/lib/red.js- /usr/lib/node_modules/node-red/red.js    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)    at Function.Module._load (internal/modules/cjs/loader.js:687:27)    at Module.require (internal/modules/cjs/loader.js:849:19)    at require (internal/modules/cjs/helpers.js:74:18)    at CameraPiTakePhotoNode._inputCallback (/home/pi/.node-red/node_modules/node-red-contrib-camerapi/camerapi.js:66:38)    at CameraPiTakePhotoNode.Node._emitInput (/usr/lib/node_modules/node-red/node_module...`

**Comment by O-Hahn** [comment]
i will create a new image on my raspy on buster .. will check the issue..

**Comment by juggledad** [comment]
Olaf, thank you for the prompt update. I just installed the new version and it works great.

One thing, it hasn't shown up in the Flow tab yet (https://flows.nodered.org/node/node-red-contrib-camerapi)

**Comment by O-Hahn** [comment]
Should be solved now
