### ISSUE TITLE
General use

### ISSUE THREAD

**Issue by jason-a69** [O-Hahn/node-red-contrib-camerapi#3]
Hi there,

Is there any documentation for this project, a couple of examples on how to use it might be a good idea. I have had a look at the code and it refers to the /home/pi/images as a default directory, how would I know that if I did not know how to code? I do not wish to be negative, and I do not mind helping, but this is not ready for release yet.

Thanks

Jason

**Comment by O-Hahn** [comment]
yes you are right - i am writing on a tutorial for the whole IoT project. I will also split the package into a raspi-toolset only (without opencv) and the face detection. I will also create the default directory by the package ...

**Comment by jason-a69** [comment]
OK, great, thanks for the positive feedback. I do not like to criticise free code, people do great things and do not get paid for it.

**Comment by ukmoose** [comment]
rather than create the default directory (which isn't specified in the readme or info) why not use the existing "Pictures" directory which is part of the default raspbian image?

**Comment by O-Hahn** [comment]
in deed - i have now switched to /home/pi/Pictures as a default directory.
