### ISSUE TITLE
label tag for Flip Picture property is unclosed

### ISSUE THREAD

**Issue by dbaba** [O-Hahn/node-red-contrib-camerapi#6]
I found a broken tag.

From https://github.com/O-Hahn/node-red-contrib-camerapi/blob/master/camerapi.html#L80
```
<label for="node-input-fliph"<i class="fa fa-repeat"></i> Flip Picture</label>
```
`>` is missing for the `label` tag.

This breaks CSS style (font) for the caption as well.

**Comment by O-Hahn** [comment]
I have fixed this broken tag.
