### ISSUE TITLE
use strict + const errors

### ISSUE THREAD

**Issue by jimwhitfield** [O-Hahn/node-red-contrib-camerapi#8]
Greetings, I just purchased a picamera to go with my RPi3 and I'm trying to add it into my NodeRed flows
When I have the trigger event, I'm having a parade of errors where ultimately I'm seeing problems with "use strict" and use of const's very soon after

(in camerapi.js]
```
/home/pi/.node-red/node_modules/node-red-contrib-camerapi/node_modules/fs-extra/lib/index.js:3
const assign = require('./util/assign')
^^^^^`
```

(in node_modules/fs-extra/lib/index.js)
```
home/pi/.node-red/node_modules/node-red-contrib-camerapi/node_modules/fs-extra/lib/index.js:3
const assign = require('./util/assign')
```
(in node_modules/fs-extra/lib/util/assign.js)
similar

(Also, just flailing around, when I removed the strict requirement in assign.js, I saw this....
```
/home/pi/.node-red/node_modules/node-red-contrib-camerapi/node_modules/fs-extra/lib/util/assign.js:7
args = [].slice.call(arguments).filter(i => i)
```

I think that's arrow notation.  Can a Raspberry Pi + node handle that?)

Thanks for any help you can offer.
Jim

**Comment by O-Hahn** [comment]
hi - on my raspi 3 the node is working well. I am running raspbian in the most current version - with nodejs 6 LTS and NPM 3. I have used the node-red upgrade script and than i have installed the node-red-contrib-camerapi. 
It seems that you have local issues with the libraries and the needed environment because i am only using fs-extra as an external lib.

**Comment by jimwhitfield** [comment]
I appreciate the reply.  Today, I cycled back around to this and found that the Pi was using the original node.js   Upgraded to 6 (and all the other required upgrades)
It compiles and runs.  I'm not always getting the behavior I want, but that's probably not a library problem.  Thanks again
