### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by andysc** [O-Hahn/node-red-contrib-camerapi#9]
/home/pi/.node-red/node_modules/node-red-contrib-camerapi/node_modules/fs-extra/lib/index.js:3
const assign = require('./util/assign')
^^^^^
2 Aug 23:41:19 - [error] [camerapi-takephoto:5d8a6535.916be4] SyntaxError: Use of const in strict mode.

This was on a Pi ZeroW
2 Aug 23:35:50 - [info] Node-RED version: v0.15.3
2 Aug 23:35:50 - [info] Node.js  version: v0.10.29

**Comment by clickworkorange** [comment]
This is probably (as it was in my case) because you're running an older version of Node.js. Read more here: https://stackoverflow.com/a/35218558/6903

**Comment by andysc** [comment]
yes, you're right :) It's working fine now - thank you.
